version: '3.8'
services:
  postgres_instance:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=document-composer
  document_composer:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres_instance:5432/document-composer
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DRIVER=org.postgresql.Driver
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on: [postgres_instance]